services:
  - type: web
    name: hr-interview-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: your_twilio_sid
      - key: TWILIO_AUTH_TOKEN
        value: your_twilio_token
      - key: TWILIO_PHONE_NUMBER
        value: your_twilio_phone_number
